### PR TITLE
Fix issue with frozen pager on iOS

### LINKED ISSUE #18: Pager tries to mutate a frozen list on iOS
During my investigation of https://github.com/rickclephas/KMP-NativeCoroutines/issues/10 I noticed the `Pager` is [updating](https://github.com/kuuuurt/multiplatform-paging/blob/d9c9a2dcc0d8880bba647728da34db7f048ba52c/paging/src/iosMain/kotlin/com/kuuurt/paging/multiplatform/Pager.kt#L61) the `PagingData` which fails when the pager is frozen.

Since there is already a `StateFlow` I think this could be easily fixed with something like the following:
```kotlin
clientScope.launch {
    val newPagingResult = getItems(key, config.pageSize)
    
    hasNextPage = newPagingResult.items.size >= config.pageSize
    _pagingData.value = PagingData<V>().apply { 
        addAll(_pagingData.value)
        addAll(newPagingResult.items)
    }
    
    currentPagingResult = newPagingResult
}
```

### PR DESCRIPTION
**Pull request by rickclephas**
Fixes #18.

Updated the pager to have a `StateFlow` containing the state of the pager.
Loading a new page will no longer modify the frozen pager but will emit a new state object instead.
The state objects are copied so they can be frozen as well.

Also added a test to verify the freezing is no longer an issue 😊.

### CODE REVIEW

File: paging/src/iosMain/kotlin/com/kuuurt/paging/multiplatform/Pager.kt [hunk 1]
```diff
@@ -21,16 +21,20 @@ actual class Pager<K : Any, V : Any> actual constructor(
     private val initialKey: K,
     private val getItems: suspend (K, Int) -> PagingResult<K, V>
 ) {
-    private val items = PagingData<V>()
 
-    private val _pagingData = MutableStateFlow<PagingData<V>?>(null)
-    actual val pagingData: Flow<PagingData<V>> get() = _pagingData.filterNotNull()
+    private data class State<K : Any, V : Any>(
```
Comment (kuuuurt) [inline paging/src/iosMain/kotlin/com/kuuurt/paging/multiplatform/Pager.kt]: Do we really have to use this `State` class? I feel that we may just be adding extra objects to manage here. Could we just use the variables instead so we can avoid `state.copy`? Or is this essential to workaround the freezing issue?

**Review by kuuuurt — CHANGES_REQUESTED** [review]

**Comment by kuuuurt** [comment]
Thanks for the contribution! Just have a question on the changes

File: paging/src/iosMain/kotlin/com/kuuurt/paging/multiplatform/Pager.kt (hunk 1 above)
Comment (rickclephas) [reply paging/src/iosMain/kotlin/com/kuuurt/paging/multiplatform/Pager.kt]: The `State` object isn't really needed for the freezing issue. It could also be accomplished with 3 separate `StateFlow` properties. The `State` object does has an extra benefit of preventing duplicate items in cases where multiple load operations are running in parallel. I am not sure if that's really useful since it will now only contain the items from the second call. Ideally I guess the calls shouldn't run in parallel anyway.

What do you think? I could change it to use 3 separate `StateFlow`s if you like.

Comment (kuuuurt) [reply paging/src/iosMain/kotlin/com/kuuurt/paging/multiplatform/Pager.kt]: I think I'd prefer that rather than adding this extra layer. Please make the changes then I'll release the next version as soon as I can 😄

**Review by kuuuurt — APPROVED** [review]
